src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Contract\Entity\TimestampableInterface;
use Knp\DoctrineBehaviors\Model\Timestampable\TimestampableTrait;

/**
 * @ORM\Entity(repositoryClass=CommentRepository::class)
 */
class Comment implements TimestampableInterface
{
    use TimestampableTrait;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Item::class, inversedBy="comments")
     */
    private $item;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="comments")
     */
    private $authorizedUser;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $anonymousUser;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $message;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getItem(): ?Item
    {
        return $this->item;
    }

    public function setItem(?Item $item): self
    {
        $this->item = $item;

        return $this;
    }

    public function getAuthorizedUser(): ?User
    {
        return $this->authorizedUser;
    }

    public function setAuthorizedUser(?User $authorizedUser): self
    {
        $this->authorizedUser = $authorizedUser;
        $this->anonymousUser = null;

        return $this;
    }

    public function getAnonymousUser(): ?string
    {
        return $this->anonymousUser;
    }

    public function setAnonymousUser(?string $anonymousUser): self
    {
        $this->authorizedUser = null;
        $this->anonymousUser = $anonymousUser;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(?string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function __toString(): string
    {
        return $this->getTitle();
    }

    public function getTitle(): string
    {
        $userTitle = $this->getUserTitle();
        $createdDate = $this->getCreatedAt()->format('d.m.Y H:i:s');

        return "$userTitle [$createdDate]";
    }

    public function getUserTitle(): string
    {
        return $this->getAuthorizedUser()
            ? $this->getAuthorizedUser()->getName()
            : 'Anonymous';
    }
}

templates/profile_marketplace/blocks/kit-agreement-notification-desktop-list-block.twig
<table class="table table-borderless table-hover">
    <thead>
    <tr>
        <th scope="col">Товари або послуги</th>
        <th scope="col">Ціна</th>
        <th scope="col">Продавці або постачальники</th>
        <th scope="col">Активно ще днів</th>
    </tr>
    </thead>
    <tbody>
    {% for product in  notification.commodity.commodities %}
        <tr>
            <td>
                <div class="proposal-info-item">
                    <a href="{{ path("#{product.commodityType}_detail",{'id':product.id}) }}">
                        <img
                                class="proposal-info-item__image large"
                                src="{{ vich_uploader_asset(product) }}"
                                alt="{{ product.title }}"
                                title="{{ product.title }}"
                        >
                    </a>
                    <div class="proposal-info-item__title">
                        <span>
                            <a href="{{ path("#{product.commodityType}_detail",{'id':product.id}) }}">
                                {{ product.title }}
                            </a>
                        </span>
                        <div class="fontSize12px">
                            <span class="grey1">ID:</span>
                            <span>{{ product.id }}</span>
                        </div>
                    </div>
                </div>
            </td>
            <td>
                <strong>
                    {{ product.price > 0
                        ? "#{product.price|numberFormatAgro} #{product|getCurrencyTitle}"
                        : 'market.product.list.priceNegotiated'|trans
                    }}
                </strong>
            </td>
            <td>
                <div class="proposal-info-item">
                    {% set usersImagesFolder    = '/upload/user/avatar' %}
                    {% set userDefaultImage     = '/main/default-avatar.png' %}
                    {% set userAvatar           = product.user and product.user.avatar
                        ? usersImagesFolder ~ '/' ~ product.user.avatar
                        : userDefaultImage %}
                    <img class="proposal-info-item__image large avatar"
                         src="{{ userAvatar }}" alt="">
                    <div class="proposal-info-item__title">
                        <span>
                            <a {% if app.user != product.user %} target="_blank" href="{{ path('market_user_detail',{'id': product.user.id}) }}"
                                   {% else %}href ="javascript:void(0)"{% endif %}>
                                            {{ product.user }}
                            </a>
                        </span>
                        <div class="fontSize12px">
                            <span class="grey1">ID:</span>
                            <span>{{ product.user.id }}</span>
                        </div>
                    </div>
                </div>
            </td>
            <td>
                <strong>{{ product.activeTo.diff((date('now'))).days }}</strong>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

templates/profile_marketplace/blocks/kit-agreement-notification-mobile-list-block.twig
<div class="proposal-info__container mobile">
    {% for product in  notification.commodity.commodities %}
        <div class="proposal-info__row proposal-info__row--bordered">
            <div>
                <div class="proposal-info__col">
                    <div class="proposal-info__col-name">Товари або послуги</div>
                    <div class="proposal-info__col-value">
                        <div class="proposal-info-item">
                            <a href="{{ path("#{product.commodityType}_detail",{'id':product.id}) }}">
                                <img
                                        class="proposal-info-item__image large"
                                        src="{{ vich_uploader_asset(product) }}"
                                        alt="{{ product.title }}"
                                        title="{{ product.title }}"
                                >
                            </a>
                            <div class="proposal-info-item__title">
                            <span>
                                <a href="{{ path("#{product.commodityType}_detail",{'id':product.id}) }}">
                                    {{ product.title }}
                                </a>
                            </span>
                                <div class="fontSize12px">
                                    <span class="grey1">ID:</span>
                                    <span>{{ product.id }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="proposal-info__col">
                    <div class="proposal-info__col-name">Ціна</div>
                    <div class="proposal-info__col-value">
                        <strong>
                            {{ product.price > 0
                                ? "#{product.price|numberFormatAgro} #{product|getCurrencyTitle}"
                                : 'market.product.list.priceNegotiated'|trans
                            }}
                        </strong>
                    </div>
                </div>
                <div class="proposal-info__col">
                    <div class="proposal-info__col-name">Продавці або постачальники</div>
                    <div class="proposal-info__col-value">
                        <div class="proposal-info-item">
                            {% set usersImagesFolder    = '/upload/user/avatar' %}
                            {% set userDefaultImage     = '/main/default-avatar.png' %}
                            {% set userAvatar           = product.user and product.user.avatar
                                ? usersImagesFolder ~ '/' ~ product.user.avatar
                                : userDefaultImage %}

                            <img class="proposal-info-item__image large avatar"
                                 src="{{ userAvatar }}" alt="">
                            <div class="proposal-info-item__title">
                                    <span>
                                        <a href="{% if app.user != product.user %}{{ path('market_user_detail',{'id': product.user.id}) }}
                                    {% else %}javascript:void(0){% endif %}">
                                            {{ product.user }}
                                        </a>
                                    </span>
                                <div class="fontSize12px">
                                    <span class="grey1">ID:</span>
                                    <span>{{ product.user.id }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="proposal-info__col">
                    <div class="proposal-info__col-name">Активно ще днів</div>
                    <div class="proposal-info__col-value">
                        <strong>{{ product.activeTo.diff((date('now'))).days }}</strong></div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

templates/profile_marketplace/blocks/my-notifications-block.html.twig
<div class="personal-area marketplace personal-area__wrapper">
    <div class="filter-wrapper">
        <a href="javascript:void(0)" class="js-mobile-filter__open filter__button">
            <svg>
                <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#filter"></use>
            </svg>
            <span>{{ 'item.filters'|trans }}</span>
        </a>
    </div>

    <div class="personal-area__inner">
        {% include 'profile_marketplace/blocks/personal-area-sidebar.html.twig' %}
        <div class="js-notification-block" data-list-ajax-url="{{ listAjaxUrl }}">
            <div class="personal-area-center__tabs-wrapper">
                <div class="personal-area-center__tab">
                    {% include 'notification/notification-filter-bar.html.twig' with {'fitler': filter} %}
                    <div class="js-select-all__list notification-list">
                        {% include 'notification/notification-block.html.twig' with {'items': items } %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'profile_marketplace/blocks/personal-area-sidebar-mobile.html.twig' %}

templates/profile_marketplace/blocks/my-notifications-trash-block.html.twig
<div class="personal-area marketplace personal-area__wrapper">
    <div class="filter-wrapper">
        <a href="javascript:void(0)" class="js-mobile-filter__open filter__button">
            <svg>
                <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#filter"></use>
            </svg>
            <span>{{ 'item.filters'|trans }}</span>
        </a>
    </div>

    <div class="personal-area__inner">
        {% include 'profile_marketplace/blocks/personal-area-sidebar.html.twig' %}
        <div class="js-notification-block" data-list-ajax-url="{{ listAjaxUrl }}">
            <div class="personal-area-center__tabs-wrapper">
                <div class="personal-area-center__tab">
                    {% include 'notification/notification-filter-bar.html.twig' with {'fitler': filter} %}
                    <div class="js-select-all__list notification-list">
                        {% include 'notification/notification-block.html.twig' with {'items': items } %}
                    </div>
                    {% if items|length > 0 %}
                        <a href="javascript:void(0)"
                           class="square-button orange-bg-button height-50
                           centeredBlock marginTop20px js-notification-bucket-clear"
                           data-url = "{{ path('notification_bucket_clear') }}"
                        >
                            Очистити кошик
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% include 'profile_marketplace/blocks/personal-area-sidebar-mobile.html.twig' %}

templates/profile_marketplace/blocks/personal-area-sidebar-mobile.html.twig
<div class="js-shade shade"></div>
<div class="js-mobile-filter mobile-filter">
    <div class="mobile-filter__inner-wrapper js-mobile-item-filter">
        <a href="javascript:void(0)" class="js-mobile-filter__close mobile-filter__close">
            <svg>
                <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#cross"></use>
            </svg>
        </a>

        <div class="marketplace-mobile-filter">
            <a class="sidebar-button" href="{{ path('market_profile_about_me') }}">
                <svg class="ico">
                    <use xlink:href="/images/smat/ico-account-edit_24x24.svg#Layer_1"></use>
                </svg>
                <span>{{ 'profile.about_me'|trans }}</span>
            </a>

            <a class="sidebar-button" href="{{ path('market_profile_my_certificates') }}">
                <svg class="ico">
                    <use xlink:href="/images/smat/ico-offer_24x24.svg#Layer_1"></use>
                </svg>
                <span>{{ 'profile.my_certificates'|trans }}</span>
            </a>

            <a class="sidebar-button" href="{{ path('market_profile_my_commodities_product') }}">
                <svg class="ico">
                    <use xlink:href="/images/smat/ico-product_24x24.svg#Layer_1"></use>
                </svg>
                <span>{{ 'profile.my_commodities'|trans }}</span>
            </a>

            <a class="sidebar-button" href="{{ path('market_profile_my_commodities_service') }}">
                <svg class="ico">
                    <use xlink:href="/images/smat/ico-room-service_24x24.svg#Layer_1"></use>
                </svg>
                <span>{{ 'profile.my_services'|trans }}</span>
            </a>

            <a class="sidebar-button" href="{{ path('market_profile_my_commodities_kit') }}">
                <svg class="ico">
                    <use xlink:href="/images/smat/ico-service-star_24x24.svg#Layer_1"></use>
                </svg>
                <span>{{ 'profile.my_joint_proposals'|trans }}</span>
            </a>

            <a class="sidebar-button" href="{{ path('market_profile_favorites_products') }}">
                <svg class="ico">
                    <use xlink:href="/images/smat/ico-heart-outline_24x24.svg#Layer_1"></use>
                </svg>
                <span>{{ 'profile.selected'|trans }}</span>
                <small>{{ userFavoritesCount != 0 ? userFavoritesCount : '' }}</small>
            </a>

            <a class="sidebar-button active" href="{{ path('my_notifications') }}">
                <div class="ico-wrapper">
                    <svg class="ico">
                        <use xlink:href="/images/smat/ico-notification_24x24.svg#Layer_1"></use>
                    </svg>
                    <div class="ico-total">{{ unreadUserNotificationCount }}</div>
                </div>
                <span>{{ 'profile.notifications'|trans }}</span>
                <small>({{ allUserNotificationCount }})</small>
            </a>

            <div class="sidebar-tail-right__dropdown">
                <a class="sidebar-button dropdown {% if trashFlag is defined and trashFlag == false %} active {% endif %}" href="{{ path('my_notifications') }}">
                    <svg class="ico">
                        <use xlink:href="/images/smat/ico-mail-in_24x24.svg#Layer_1"></use>
                    </svg>
                    <span>Вхідні</span>
                    <small>({{ allUserNotificationCount }})</small>
                </a>

                <a class="sidebar-button dropdown {% if trashFlag is defined and trashFlag == true%} active {% endif %}" href="{{ path('my_notifications_trash') }}">
                    <svg class="ico">
                        <use xlink:href="/images/smat/ico-delete_24x24.svg#Layer_1"></use>
                    </svg>
                    <span>Кошик</span>
                    <small>({{ trashedUserNotificationCount }})</small>
                </a>
            </div>

            <a class="sidebar-button" href="{{ path('market_profile_roles') }}">
                <svg class="ico">
                    <use xlink:href="/images/smat/ico-bookmarks_24x24.svg#Layer_1"></use>
                </svg>
                <span>{{ 'profile.my_roles'|trans }}</span>
            </a>
        </div>
    </div>
</div>

templates/profile_marketplace/blocks/personal-area-sidebar.html.twig
<div class="personal-area-sidebar">
    <div class="personal-area-sidebar__content">
        <div class="personal-area-sidebar__tabs-navigation">
            <a class="btn-sidebar-tail-right" href="{{ path('market_profile_about_me') }}">
                <svg class="ico">
                    <use xlink:href="/images/smat/ico-account-edit_24x24.svg#Layer_1"></use>
                </svg>
                <span>{{ 'profile.about_me'|trans }}</span>
            </a>

            <a class="btn-sidebar-tail-right" href="{{ path('market_profile_my_certificates') }}">
                <svg class="ico">
                    <use xlink:href="/images/smat/ico-offer_24x24.svg#Layer_1"></use>
                </svg>
                <span>{{ 'profile.my_certificates'|trans }}</span>
            </a>

            <a class="btn-sidebar-tail-right" href="{{ path('market_profile_my_commodities_product') }}">
                <svg class="ico">
                    <use xlink:href="/images/smat/ico-product_24x24.svg#Layer_1"></use>
                </svg>
                <span>{{ 'profile.my_commodities'|trans }}</span>
            </a>

            <a class="btn-sidebar-tail-right" href="{{ path('market_profile_my_commodities_service') }}">
                <svg class="ico">
                    <use xlink:href="/images/smat/ico-room-service_24x24.svg#Layer_1"></use>
                </svg>
                <span>{{ 'profile.my_services'|trans }}</span>
            </a>

            <a class="btn-sidebar-tail-right" href="{{ path('market_profile_my_commodities_kit') }}">
                <svg class="ico">
                    <use xlink:href="/images/smat/ico-service-star_24x24.svg#Layer_1"></use>
                </svg>
                <span>{{ 'profile.my_joint_proposals'|trans }}</span>
            </a>

            <a class="btn-sidebar-tail-right" href="{{ path('market_profile_favorites_products') }}">
                <svg class="ico">
                    <use xlink:href="/images/smat/ico-heart-outline_24x24.svg#Layer_1"></use>
                </svg>
                <span>{{ 'market.profile.menu.favorites'|trans }}</span>
                <small>{{ userFavoritesCount != 0 ? userFavoritesCount : '' }}</small>
            </a>

            <a class="btn-sidebar-tail-right active" href="{{ path('my_notifications') }}">
                <div class="ico-wrapper">
                    <svg class="ico">
                        <use xlink:href="/images/smat/ico-notification_24x24.svg#Layer_1"></use>
                    </svg>
                    <div class="ico-total">{{ unreadUserNotificationCount }}</div>
                </div>
                <span>{{ 'profile.notifications'|trans }}</span>
                <small>({{ allUserNotificationCount }})</small>
            </a>

            <div class="sidebar-tail-right__dropdown">
                <a class="btn-sidebar-tail-right dropdown{% if trashFlag is defined and trashFlag == false%} active {% endif %}" href="{{ path('my_notifications') }}">
                    <svg class="ico">
                        <use xlink:href="/images/smat/ico-mail-in_24x24.svg#Layer_1"></use>
                    </svg>
                    <span>Вхідні</span>
                    <small>({{ activeUserNotificationCount }})</small>
                </a>

                <a class="btn-sidebar-tail-right dropdown {% if trashFlag is defined and trashFlag == true%} active {% endif %}" href="{{ path('my_notifications_trash') }}">
                    <svg class="ico">
                        <use xlink:href="/images/smat/ico-delete_24x24.svg#Layer_1"></use>
                    </svg>
                    <span>Кошик</span>
                    <small>({{ trashedUserNotificationCount }})</small>
                </a>
            </div>

            <a class="btn-sidebar-tail-right" href="{{ path('market_profile_roles') }}">
                <svg class="ico">
                    <use xlink:href="/images/smat/ico-bookmarks_24x24.svg#Layer_1"></use>
                </svg>
                <span>{{ 'profile.my_roles'|trans }}</span>
            </a>
        </div>
    </div>
</div>

templates/profile_marketplace/blocks/proposal-summary-table-block.html.twig
<div class="proposal-info">
    {% if notification.title %}
        <div>
            <h4 class="h4 marginBottom20px">  {% if notification.commodity.isActive%}
                <a href="{{ path(notification.commodity.commodityType ~'_detail',
                    {'id':notification.commodity.id}) }}">
                    Тема: {{ notification.title }}
                </a>
                {% else %}
                    Тема: {{ notification.title }}
                {% endif %}</h4>
        </div>
    {% endif %}
    <div class="proposal-info-item marginBottom40px">
        <div class="js-row proposal-info-item__title fontSize17-20px">
        </div>
    </div>
    {% include 'profile_marketplace/blocks/kit-agreement-notification-mobile-list-block.twig' %}
    {% include 'profile_marketplace/blocks/kit-agreement-notification-desktop-list-block.twig' %}
    <div class="proposal-info__footer">
        <div class="proposal-info__row">
            <div class="proposal-info__col-name">Контакти</div>
            <div class="proposal-info__col-value">{{ notification.sender.email }}</div>
            <div class="proposal-info__col-value">{{ notification.phone ?? notification.sender.phone }}</div>
        </div>

        <div class="proposal-info__row">
            <div class="proposal-info__col-name">Повідомлення дійсне до:</div>
            <div class="proposal-info__col-value">
                <div class="proposal-info__period">
                    <div class="fontSize15-20px green"> <br>
                        {{ notification.commodity.activeTo | format_datetime() }}
                    </div>
                </div>
            </div>
        </div>

        {% set summary = 0 %}
        {% for commodity in notification.commodity.commodities%}
            {% set summary = summary + commodity.price %}
        {% endfor %}
        <div class="proposal-info__row">
            <div class="product-price-item">

                <div class="proposal-info__col-name">
                    {{ 'market.profile.kitForm.summaryInformation.commoditySummary'|trans }}
                </div>
                <div class="grey1">
                    <strong class="fontSize20px">
                        {{ summary|numberFormatAgro }}
                    </strong>
                    {{ 'market.currency.short'|trans }}
                </div>
                <br>

                <div class="proposal-info__col-name">
                    {{ 'market.profile.kitForm.summaryInformation.kitPrice'|trans }}
                </div>
                <div class="green">
                    <strong class="fontSize30px">
                        {{ notification.commodity.price > 0
                            ? "#{notification.commodity.price|numberFormatAgro} #{notification.commodity|getCurrencyTitle}"
                            : 'market.product.list.priceNegotiated'|trans
                        }}
                    </strong>
                </div>
            </div>
        </div>
    </div>
</div>