src/Entity/News.php
<?php
declare(strict_types=1);

namespace App\Entity;

use RuntimeException;
use SplFileInfo;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\{
    ArrayCollection,
    Collection,
};
use App\Repository\NewsRepository;
use Knp\DoctrineBehaviors\Contract\Entity\TranslatableInterface;
use Knp\DoctrineBehaviors\Model\Translatable\TranslatableTrait;
use Vich\UploaderBundle\{
    Entity\File,
    Mapping\Annotation as Vich
};
use App\Traits\{
    EmptyField,
    Trans,
};
use App\Service\FileManager\FileManagerInterface;
use App\Validator as AcmeAssert;
/**
 * @ORM\Entity(repositoryClass=NewsRepository::class)
 * @AcmeAssert\TranslationLength()
 * @Vich\Uploadable
 */
class News extends Item implements TranslatableInterface
{
    use TranslatableTrait;
    use Trans;
    use EmptyField;

    /**
     * @Vich\UploadableField(mapping="news_image", fileNameProperty="imageName")
     *
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", nullable=true)
     *
     * @var string|null
     */
    private $imageName;

    /**
     * @ORM\ManyToOne(targetEntity=Region::class, inversedBy="news")
     */
    private $region;

    /**
     * @ORM\ManyToMany(targetEntity=Item::class, inversedBy="similarNewsRelation")
     */
    private $similar;

    public function __construct()
    {
        parent::__construct();
        $this->similar = new ArrayCollection();
    }

    /**
     * @inheritDoc
     */
    public function getTypeItem(): string
    {
        return self::NEWS;
    }

    public function __toString(): string
    {
        return $this->proxyCurrentLocaleTranslation('getTitle');
    }

    public function setImageFile($imageFile = null): void
    {

        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function getRegion(): ?Region
    {
        return $this->region;
    }

    public function setRegion(?Region $region): self
    {
        $this->region = $region;

        return $this;
    }

    /**
     * @inheritDoc
     */
    public function getCopy(
        ParameterBagInterface $parameters,
        FileManagerInterface $fileManager
    ): self {
        $result = parent::getCopy($parameters, $fileManager);

        $result->setTypePage($this->getTypePage());
        $result->setRegion($this->getRegion());
        $result->copyTranslations($this);

        if ($this->getImageName()) {
            $kernelRoot = $parameters->get('kernel.project_dir');
            $imagesDirectoryPath = $parameters->get('app.entity.files.article');
            $imagesDirectory = new SplFileInfo($kernelRoot . $imagesDirectoryPath);
            $image = new SplFileInfo(
                $imagesDirectory->getPathname() .
                DIRECTORY_SEPARATOR .
                $this->getImageName()
            );

            try {
                $imageCopy = $fileManager->copyEntityFile($image, $imagesDirectory);
                $result->setImageName($imageCopy->getFilename());
            } catch (RuntimeException $exception) {

            }
        }

        return $result;
    }

    /**
     * @return Collection|self[]
     */
    public function getSimilar(): Collection
    {
        return $this->similar;
    }

    public function addSimilar(?Item $similar): self
    {
        if (!$this->similar->contains($similar)) {
            $this->similar[] = $similar;
        }

        return $this;
    }

    public function removeSimilar(self $similar): self
    {
        $this->similar->removeElement($similar);

        return $this;
    }

    public function getItemCropsAndCategoriesIds():array
    {
        $data = [];
        if ($this->getCategory()) $data['categoryId'] = $this->getCategory();
        if (!$this->getCrops()->isEmpty()) {
            foreach ($this->getCrops() as $crop) {
                $data['cropsIds'][] = $crop->getId();
            }
        }
        $data['id'] = $this->getId();

        return $data;
    }
}

src/Entity/Tags.php
<?php

namespace App\Entity;

use App\Repository\TagsRepository;
use App\Traits\Trans;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Contract\Entity\TimestampableInterface;
use Knp\DoctrineBehaviors\Contract\Entity\TranslatableInterface;
use Knp\DoctrineBehaviors\Model\Timestampable\TimestampableTrait;
use Knp\DoctrineBehaviors\Model\Translatable\TranslatableTrait;

/**
 * @ORM\Entity(repositoryClass=TagsRepository::class)
 */
class Tags implements TranslatableInterface, TimestampableInterface
{
    use TranslatableTrait;
    use TimestampableTrait;
    use Trans;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToMany(targetEntity=Item::class, mappedBy="tags")
     */
    private $items;

    /**
     * @ORM\ManyToMany(targetEntity=Expert::class, mappedBy="tags")
     */
    private $experts;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, mappedBy="tags")
     */
    private $categories;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $slug;

    public function __construct()
    {
        $this->items = new ArrayCollection();
        $this->experts = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->proxyCurrentLocaleTranslation('getName');
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|Item[]
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    public function addItem(Item $item): self
    {
        if (!$this->items->contains($item)) {
            $this->items[] = $item;
            $item->addTag($this);
        }

        return $this;
    }

    public function removeItem(Item $item): self
    {
        if ($this->items->removeElement($item)) {
            $item->removeTag($this);
        }

        return $this;
    }

    /**
     * @return Collection|Expert[]
     */
    public function getExperts(): Collection
    {
        return $this->experts;
    }

    public function getExpertsCount(): int
    {
        return $this->experts->count();
    }

    public function addExpert(Expert $expert): self
    {
        if (!$this->experts->contains($expert)) {
            $this->experts[] = $expert;
        }

        return $this;
    }

    public function removeExpert(Expert $expert): self
    {
        $this->experts->removeElement($expert);

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->addTag($this);
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->removeElement($category)) {
            $category->removeTag($this);
        }

        return $this;
    }
}

src/Controller/TagsController.php
<?php
declare(strict_types=1);

namespace App\Controller;

use Symfony\Component\HttpFoundation\{
    Request,
    Response,
};
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Knp\Component\Pager\PaginatorInterface;
use App\Helper\SeoHelper;
use App\Entity\{
    Item,
    Page,
    Tags,
};
/**
 * Class TagsController
 * @package App\Controller
 */
class TagsController extends AbstractController
{
    private const PAGE_SIZE = 24;
    /**
     * @Route("/tag/{slug}", name="tag_detail")
     *
     * @param string $slug
     * @param PaginatorInterface $paginator
     * @param Request $request
     *
     * @return Response
     */
    public function detail(string $slug, PaginatorInterface $paginator, Request $request): Response
    {
        /** @var Tags $tag */
        $tag            = $this
            ->getDoctrine()
            ->getRepository(Tags::class)
            ->findOneBy([
                'slug' => $slug,
            ]);

        if (!$tag) {
            throw new NotFoundHttpException("item $tag was not found");
        }

        $tagItems       = $this->getTagItems($tag);
        $currentPage    = $request->query->getInt('page', 1);
        $pagination     = $paginator->paginate($tagItems, $currentPage, self::PAGE_SIZE);
        $lastModified   = SeoHelper::formatLastModified($tag->getUpdatedAt());
        $response       = new Response();
        $response->headers->set('Last-Modified', $lastModified);

        return $this->render('tag/detail.html.twig', [
            'tag'       => $tag,
            'items'     => $pagination,
            'pagesList' => $this
                ->getDoctrine()
                ->getRepository(Page::class)
                ->findPageByTypeName('business_tools'),
        ], $response);
    }
    /**
     * Get tag items.
     *
     * @param   Tags $tag   Tag.
     *
     * @return  Item[]      Tag items set.
     */
    private function getTagItems(Tags $tag): iterable
    {
        $alias          = 'item';
        $aliasTags      = 'tag';
        $queryBuilder   = $this
            ->getDoctrine()
            ->getRepository(Item::class)
            ->createQueryBuilder($alias);

        $queryBuilder
            ->leftJoin("$alias.tags", $aliasTags)
            ->orderBy("$alias.createdAt", 'DESC')
            ->andWhere(
                $queryBuilder->expr()->eq("$alias.isActive", true)
            )
            ->andWhere(
                $queryBuilder->expr()->eq("$aliasTags.id", ':tag')
            )
            ->setParameter('tag', $tag->getId());

        return $queryBuilder->getQuery()->getResult();
    }
}

templates/tag/detail.html.twig
{% extends 'layout/content.html.twig' %}

{% block title %}{{ 'search.result'|trans }}{% endblock %}

{% block body %}
    <div class="section">
        <h1 class="h1 marginBottom40px"><strong>{{ tag.name }}</strong></h1>

        {% if (items|length > 0) %}
            <div class="popular-topics">
                <ul class="popular-topics__items-wrap">
                    {% for item in items %}
                        {% set href = "" %}
                        {% if item.typeItem == constant('App\\Entity\\Item::COURSE') %}
                            {% set href = path('course_detail', {'slug': item.slug}) %}
                        {% elseif item.typeItem == constant('App\\Entity\\Item::WEBINAR') %}
                            {% set href = path('webinar_detail', {'slug': item.slug}) %}
                        {% elseif item.typeItem == constant('App\\Entity\\Item::OTHER') %}
                            {% set href = path('article_detail', {'slug': item.slug}) %}
                        {% elseif item.typeItem == constant('App\\Entity\\Item::OCCURRENCE') %}
                            {% set href = path('occurrence_detail', {'slug': item.slug}) %}
                        {% elseif item.typeItem == constant('App\\Entity\\Item::NEWS') %}
                            {% set href = path('news_detail', {'slug': item.slug}) %}
                        {% elseif item.typeItem == constant('App\\Entity\\Item::ARTICLE') %}
                            {% if item.typePage.code == 'article' %}
                                {% set href = path('article_detail', {'slug': item.slug}) %}
                            {% elseif item.typePage.code == 'success_stories' %}
                                {% set href = path('article_detail', {'slug': item.slug}) %}
                            {% elseif item.typePage.code == 'eco_articles' %}
                                {% set href = path('article_detail', {'slug': item.slug}) %}
                            {% endif %}
                        {% endif %}
                        <li class="popular-topics__item">
                            <a class="popular-topics__link" href="{{ href }}">
                                <span class="popular-topics__date">
                                    {{ item.createdAt|date("Y m d") }}
                                </span>
                                <span class="popular-topics__text">
                                    {{ item.title }}
                                </span>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="navigation">
                {{ knp_pagination_render(items) }}
            </div>
        {% else %}
            <div class="h3 centeredBlock">{{ 'not-found'|trans }}</div>
        {% endif %}
    </div>

    {% include 'blocks/business-tools-lite-block.html.twig' %}
    {% include 'blocks/catalog-block.html.twig' %}
    {# {% include 'blocks/knowledge-base-block.html.twig' with {'categories': categories} %} #}
{% endblock %}